---
homebrew:

  taps:
    - homebrew/versions
    - homebrew/completions
    - homebrew/binary
    - homebrew/php
    - caskroom/versions
    - caskroom/fonts
    - thoughtbot/formulae
    - laurent22/massren
    - sanemat/font
    - mackerelio/mackerel-agent

  packages:
    - { name: ag }
    - { name: awscli }
    - { name: bash }
    - { name: bash-completion }
    - { name: bfg }
    - { name: cliclick }
    - { name: ctags }
    - { name: direnv }
    - { name: fish }
    - { name: ghq }
    - { name: git }
    - { name: gitsh }
    - { name: git-extras }
    - { name: go }
    - { name: gnu-sed }
    - { name: heroku }
    - { name: htop }
    - { name: hub }
    - { name: imagemagick }
    - { name: jq }
    - { name: lua }
    - { name: mackerel-agent }
    - { name: markdown }
    - { name: massren }
    - { name: mongodb }
    - { name: node }
    - { name: packer }
    - { name: php56 }
    - { name: composer }
    - { name: phantomjs }
    - { name: peco }
    - { name: pv }
    - { name: python }
    - { name: rails-completion }
    - { name: reattach-to-user-namespace }
    - { name: rbenv }
    - { name: rename }
    - { name: ripgrep }
    - { name: ruby-build }
    - { name: tag }
    - { name: terraform }
    - { name: tmux }
    - { name: tree }
    - { name: trash }
    - { name: unrar }
    - { name: vagrant-completion }
    - { name: webkit2png }
    - { name: wget }
    - { name: yarn }
    - { name: z }
    - { name: zsh, install_options: without-etcdir }

  casks:
    - 1password
    - adobe-air
    - adobe-photoshop-cc
    - adoptopenjdk
    - alfred
    - appcleaner
    - atom
    - blisk
    - dash
    - bettertouchtool
    - betterzipql
    - chatwork
    - clamxav
    - cyberduck
    - docker
    - dropbox
    - duet
    - evernote
    - firefox
    - falcon-sql-client
    - github-desktop
    - google-chrome
    - google-chrome-canary
    - google-japanese-ime
    - hyper
    - iina
    - imagealpha
    - imageoptim
    - istat-menus
    - iterm2
    - karabiner
    - keycastr
    - opera
    - processing
    - provisionql
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - qlstephen
    - qlprettypatch
    - quicklook-csv
    - quicklook-json
    - recordit
    - sequel-pro
    - simple-comic
    - skitch
    - sqlitebrowser
    - skype
    - slack
    - soundflower
    - sourcetree
    - spotify
    - sublime-text
    - suspicious-package
    - teleport
    - the-unarchiver
    - unity
    - vagrant
    - virtualbox
    - vmware-fusion
    - webpquicklook
    - xld

npm:
  - bower
  - eslint
  - gulp-cli
  - yo

gem:
  - bundler
  - travis
