---
homebrew:

  taps:
    - homebrew/versions
    - homebrew/completions
    - homebrew/binary
    - homebrew/php
    - caskroom/versions
    - caskroom/fonts
    - thoughtbot/formulae
    - laurent22/massren
    - sanemat/font

  packages:
    - { name: ag }
    - { name: awscli }
    - { name: bash }
    - { name: bash-completion }
    - { name: casperjs }
    - { name: cliclick }
    - { name: ctags }
    - { name: direnv }
    - { name: ghq }
    - { name: git }
    - { name: gitsh }
    - { name: git-extras }
    - { name: go }
    - { name: googlecl }
    - { name: gnu-sed }
    - { name: hub }
    - { name: imagemagick }
    - { name: jq }
    - { name: lua }
    - { name: markdown }
    - { name: massren }
    - { name: mongodb }
    - { name: node }
    - { name: packer }
    - { name: php56 }
    - { name: composer }
    - { name: phantomjs }
    - { name: peco }
    - { name: pv }
    - { name: python }
    - { name: rails-completion }
    - { name: rbenv }
    - { name: rename }
    - { name: ruby-build }
    - { name: tag }
    - { name: tree }
    - { name: trash }
    - { name: unrar }
    - { name: vagrant-completion }
    - { name: webkit2png }
    - { name: wget }
    - { name: z }
    - { name: zsh, install_options: without-etcdir }

  casks:
    - 1password
    - adobe-air
    - alfred
    - appcleaner
    - atom
    - dash
    - bettertouchtool
    - betterzipql
    - clamxav
    - cyberduck
    - dropbox
    - duet
    - evernote
    - firefox
    - github-desktop
    - google-chrome
    - google-chrome-canary
    - google-japanese-ime
    - heroku-toolbelt
    - hyperswitch
    - imagealpha
    - imageoptim
    - istat-menus
    - iterm2
    - karabiner
    - keycastr
    - lastfm
    - nitrous-desktop
    - onyx
    - opera
    - provisionql
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - qlstephen
    - qlprettypatch
    - quicklook-csv
    - quicklook-json
    - sequel-pro
    - sharemouse
    - skype
    - sublime-text
    - suspicious-package
    - techstoreclub-simple-comic
    - teleport
    - the-unarchiver
    - vagrant
    - virtualbox
    - vmware-fusion
    - vlc
    - webpquicklook
    - xld

npm:
  - bower
  - eslint
  - gulp-cli
  - grunt
  - n
  - yo

gem:
  - bundler
  - compass
  - sass
  - serverspec
  - slim
  - travis
