---
homebrew:

  taps:
    - homebrew/versions
    - homebrew/completions
    - homebrew/binary
    - caskroom/versions
    - caskroom/fonts
    - thoughtbot/formulae
    - laurent22/massren
    - sanemat/font
    - peco/peco
    - motemen/ghq

  packages:
    - ag
    - ansible
    - awscli
    - bash
    - bash-completion
    - casperjs
    - cliclick
    - ctags
    - ghq
    - git
    - gitsh
    - googlecl
    - gnu-sed
    - hub
    - imagemagick
    - jq
    - lua
    - markdown
    - massren
    - mongodb
    - node
    - packer
    - phantomjs
    - peco
    - pv
    - python
    - rails-completion
    - rbenv
    - rename
    - ruby-build
    - tag
    - tree
    - trash
    - unrar
    - unar
    - vagrant-completion
    - vagrant-completion
    - webkit2png
    - wget
    - z
    - zsh

  docker:
    - boot2docker
    - docker
    - fig

  casks:
    - 1password
    - adobe-air
    - atom
    - dash
    - bettertouchtool
    - betterzipql
    - dropbox
    - clamxav
    - cyberduck
    - evernote
    - firefox
    - github
    - google-chrome
    - google-chrome-canary
    - hyperswitch
    - imagealpha
    - imageoptim
    - istat-menus
    - iterm2
    - karabiner
    - lastfm
    - nitrous-desktop
    - onyx
    - opera
    - provisionql
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - qlstephen
    - qlprettypatch
    - quicklook-csv
    - quicklook-json
    - skype
    - simple-comic
    - sublime-text
    - suspicious-package
    - the-unarchiver
    - tinkertool
    - vagrant
    - virtualbox
    - vmware-fusion
    - vlc
    - webpquicklook

npm:
  - bower
  - gulp-cli
  - grunt
  - n
  - yo

gem:
  - bundler
  - compass
  - sass
  - serverspec
